# Use Brandon's Ruby base image (includes jemalloc)
FROM brandoncabael/docker-ruby-2.7:2.7.1

# Baller maintainer
LABEL maintainer "Brandon Cabael <brandon.cabael@gmail.com>"

# Set EDITOR default to vim (used when editing env via sops)
ENV EDITOR vim

# Use generic /app path for working directory
ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

# Run system package installations
RUN set -ex && \
      # Update apt-get and start install cmd
      apt-get update && apt-get install -qq -y --no-install-recommends \
      # Basic required packages for all rails images
      build-essential git vim gnupg2 && \
      # Update bundler gem
      gem install bundler

RUN set -ex && \
      # Placeholder for conditional packages (changes based on variant, generated by update.sh)
      apt-get install -qq -y --no-install-recommends libpq-dev ghostscript libvips libvips-dev graphviz

COPY vimrc /root/.vimrc

CMD bundle exec jets server --host 0.0.0.0