# Use Bowtie Ruby base image (includes jemalloc)
FROM brandoncabael/docker-ruby-2.7

# Baller maintainers
LABEL maintainer "Charlie McClung <charlie@bowtie.co>, Brandon Cabael <brandon@bowtie.co>"

# Set EDITOR default to vim (used when editing env via sops)
ENV EDITOR vim

# Use generic /app path for working directory
ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

ENV NODE_SHA 2141b38337b282360bc79561bedbc0ce5b0c43aed52b7f7e897e5ce0654700e2

# Download installers for node 8.x
ADD https://deb.nodesource.com/setup_12.x /tmp/node.sh

# Run system package installations
RUN set -ex && \
      # Verify downloaded node.sh SHA
      echo "$NODE_SHA /tmp/node.sh" | sha256sum -c - && \
      # Update apt-get and start install cmd
      apt-get update && apt-get install -qq -y --no-install-recommends \
      # Basic required packages for all rails images
      build-essential git vim gnupg2 && \
      # Install node (only installs 8.x apt repo & key)
      cat /tmp/node.sh | bash && \
      # Run install again for nodejs (after running node.sh, this will install 8.x)
      apt-get install -qq -y -f --no-install-recommends nodejs && \
      # Update bundler gem
      gem install bundler && \
      # Remove tmp install files
      rm /tmp/node.sh

RUN set -ex && \
      # Placeholder for conditional packages (changes based on variant, generated by update.sh)
      apt-get install -qq -y --no-install-recommends libpq-dev ghostscript libvips libvips-dev graphviz

COPY vimrc /root/.vimrc

CMD bundle exec puma -C config/puma.rb